Update index.html
htmlacademy-htmlcss/1874843-device-33 pull request #2
Opened 2022-01-21 17:13 UTC by InnokentyKedrov

2022-01-22 10:39 UTC, InnokentyKedrov commented
Внесены изменения в index.html. Добавлен файл catalog.html.

2022-01-23 14:19 UTC, mouxez requested changes

2022-01-23 14:19 UTC, mouxez commented on catalog.html
> +          <a class="breadcrumbs-link" href="catalog.html">Каталог товаров</a>
как правило страница на должна иметь ссылку на саму себя в навигационном меню. тут подойдёт заглушка для href

2022-01-23 14:19 UTC, mouxez commented on catalog.html
> +    <form class="search" action="https://echo.htmlacademy.ru/" method="post">
вот тут хорошо объясняют, когда лучше использовать GET и POST methods
https://stackoverflow.com/questions/504947/when-should-i-use-get-or-post-method-whats-the-difference-between-them#:~:text=In%20plain%20English%2C%20that%20means,your%20password%20should%20use%20POST.

2022-01-23 14:19 UTC, mouxez commented on catalog.html
> +    <form class="search" action="https://echo.htmlacademy.ru/" method="post">
тут больше подходит GET

2022-01-23 14:19 UTC, mouxez commented on catalog.html
> +          <b class="product-card-price">500 ₽</b>
стилизовать текст надо через CSS
нужно убрать тэг b

2022-01-23 14:19 UTC, mouxez commented on catalog.html
> +    <img class="footer-logo" src="" alt="Логотип магазина Device">
если ссылка не известна или карт нки пока нет, можно ставить заглушку отсюда https://placeholder.com/

2022-01-23 14:19 UTC, mouxez commented on catalog.html
> +    <img class="footer-logo" src="" alt="Логотип магазина Device">
пустым src="" лучше не оставлять

2022-01-23 14:19 UTC, mouxez commented on index.html
> +        <input class="search-field" type="text" name="search-field" placeholder="Текст поиска" type="text">
лишний атрибут type="text"

2022-01-23 14:19 UTC, mouxez commented on index.html
> +          <input class="subscription-field" type="text" name="subscription-field" placeholder="Ваш e-mail" type="email">
лишний атрибут type="text"

2022-01-23 16:27 UTC, InnokentyKedrov commented on catalog.html
> +          <a class="breadcrumbs-link" href="catalog.html">Каталог товаров</a>
Заглушку поставил. Тут я просто думал этой ссылкой попадать на начальное состояние страницы catalog - опять думал лишнего)

2022-01-23 16:27 UTC, InnokentyKedrov commented on catalog.html
> +    <form class="search" action="https://echo.htmlacademy.ru/" method="post">
Ок

2022-01-23 16:28 UTC, InnokentyKedrov commented on catalog.html
> +          <b class="product-card-price">500 ₽</b>
Поставил вместо b тег span.

2022-01-23 16:30 UTC, InnokentyKedrov commented on index.html
> +        <input class="search-field" type="text" name="search-field" placeholder="Текст поиска" type="text">
Убрал

2022-01-23 16:30 UTC, InnokentyKedrov commented on catalog.html
> +    <img class="footer-logo" src="" alt="Логотип магазина Device">
Видел что validator выдаёт ошибку, просто на лайве Андрей показывал это и сказал забить) Но заглушки я поставил.

2022-01-23 16:30 UTC, InnokentyKedrov commented on index.html
> +          <input class="subscription-field" type="text" name="subscription-field" placeholder="Ваш e-mail" type="email">
Убрал

2022-01-23 16:31 UTC, InnokentyKedrov commented
Исправил недостатки

2022-01-24 06:35 UTC, merged